#!/usr/bin/env node
'use strict';

// test-bgP7.js — BG-P7 (Profile 7.7, BR-106; RULINGS P7, BF13, BF17, 12:05 #6, #9): SSSOM validity of the exporter's TSV.
//   (a) the TSV parses — the framework's OWN header/row/curie_map validator, LABELLED PROXY (RULING 12:05 #6), runs always;
//   sssom-py was absent at B2 (checked 2026-08-16) and is PRESENT since B3 cp2 in the ONE-MACHINE venv (SSSOM_PY_BIN_PATH
//   below) — the REAL validator runs beside the proxy when present and says so by name (BR3-8); (b) every
//   non-built-in prefix is in curie_map; (c) object_match_field is the Profile §4.5 tuple string on every row; (d)
//   subject_match_field names the DOCUMENT prefix for crosswalk (toyCrosswalk:HubGlobalId|toyCrosswalk:HubClassURI) and the
//   standard's own prefix + property NAME for standard (toy:hubAnchorId — CURIE-safe, never a header text); (e)
//   mapping_date present ONLY if a declared source column supplied it (none in v1 — an exporter stamping today is refused);
//   (f) mapping_provider recorded as verified (verifiedBy null → the export REFUSES the run); (g) author_id / creator_id
//   emitted at set level whenever declared. Plus the report's subject census beside the row count (RULING 12:05 #9).
//
// Run: node lib/bridge-framework/test/test-bgP7.js [-verbose]

const moduleName = __filename.replace(__dirname + '/', '').replace(/.js$/, '');
const helpText = () => `
NAME
     ${moduleName} -- BG-P7: SSSOM/TSV validity (PROXY validator always; the REAL sssom-py beside it when its venv is present — it IS, under system/dataStores/bridgeAcceptance/sssomVenv since B3 cp2)

SYNOPSIS
     ${moduleName} [-verbose] [-quiet] [-help]

EXIT STATUS
     0 all conjuncts PASS and every conjunct was observed RED under its twin;  1 otherwise.
`;
require('../../../test/testLib/testAppStartup')({ moduleName, helpText: helpText() });
const harness = require('../../../test/testLib/harness')(moduleName);

const path = require('path');
const fs = require('fs');
const scenarioLib = require('./testSupport/toyBridgeScenario');
const { runConjunct, succeeded, nameInRefusal, refusalCase, frameworkMutationTwin, scenarioTwin } = require('./testSupport/bridgeTwinFactories');
const { runGateFamily } = require(path.join(__dirname, '..', '..', 'forge-framework', 'test', 'testSupport', 'gateSuiteRunner'));
const { makeTwinRegistry } = require(path.join(__dirname, '..', '..', 'forge-framework', 'roundTripHarness', 'twinRegistry'));
const moduleDouble = require(path.join(__dirname, '..', '..', 'forge-framework', 'test', 'testSupport', 'moduleDouble'));
const sssomExporterLib = require('../sssomExporter');

const GATE_ID = 'BG-P7';
const twinRegistry = makeTwinRegistry();
const EXPORTER_FILE = 'sssomExporter.js';
const FRAMEWORK_FILE = 'bridge-framework.js';
const CROSSWALK_PLUGIN_PATH = path.join(scenarioLib.FIXTURE_FORGES_DIR, 'toy', 'bridges', 'toyCrosswalkPlugin.js');
const VALIDATOR_LABEL = 'PROXY (framework header/row/curie_map validator; sssom-py runs beside it when its venv is present — RULING 12:05 #6, B3 cp2)';
// sssom-py (ONE-MACHINE): the B3 venv under system/dataStores/bridgeAcceptance/sssomVenv — the REAL validator runs when present, the PROXY otherwise, and says which
const SSSOM_PY_BIN_PATH = path.join(scenarioLib.FRAMEWORK_DIR, '..', '..', '..', '..', 'dataStores', 'bridgeAcceptance', 'sssomVenv', 'bin', 'sssom');
const SSSOM_PY_PRESENT = fs.existsSync(SSSOM_PY_BIN_PATH);
const SSSOM_PY_LABEL = SSSOM_PY_PRESENT ? `sssom-py present at ${SSSOM_PY_BIN_PATH} — ONE-MACHINE` : 'sssom-py ABSENT — PROXY only';
const cloneJson = scenarioLib.cloneJson;
const tsvOf = (outcome) => fs.readFileSync(outcome.runReport.sssomExportPath, 'utf8');
const parsedOf = (outcome, scenario) => {
	const lib = scenario.frameworkMutationList.some((oneMutation) => oneMutation.modulePath.endsWith(EXPORTER_FILE)) ? moduleDouble.loadWithMutations({ modulePath: path.join(scenarioLib.FRAMEWORK_DIR, EXPORTER_FILE), mutationList: scenario.frameworkMutationList }) : sssomExporterLib;
	return lib.parseSssomTsv(tsvOf(outcome));
};
const overrideDeclaration = (scenario, mutate) => {
	const loaded = require(CROSSWALK_PLUGIN_PATH);
	const bridgeDeclaration = cloneJson(loaded.bridgeDeclaration);
	mutate(bridgeDeclaration);
	scenario.pluginModuleOverrides.toyCrosswalkPlugin = { bridgeDeclaration };
};

const conjunctList = [
	runConjunct({ conjunctId: 'a_tsvParses_PROXY', title: `the TSV parses — ${VALIDATOR_LABEL}: mandatory columns present, every row the header's width, a #curie_map block`, twinNameList: ['deleteMandatoryColumn'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); return { pass: !parsed.error && parsed.rowList.length === runReport.edgesWritten && parsed.headerLineList.some((oneLine) => oneLine === '#curie_map:'), detail: parsed.error || `${parsed.rowList.length} rows / ${parsed.columnList.length} columns [${VALIDATOR_LABEL}]` }; }) }),
	runConjunct({ conjunctId: 'b_everyPrefixInCurieMap', title: 'every non-built-in prefix used (subject_id, match fields) is declared in curie_map', twinNameList: ['dropHubPrefixFromCurieMap'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const declared = parsed.headerLineList.filter((oneLine) => /^#  \w+: /.test(oneLine)).map((oneLine) => oneLine.replace(/^#  (\w+): .*/, '$1')); const usedList = Array.from(new Set(parsed.rowList.reduce((soFar, oneRow) => soFar.concat([oneRow.subject_id.split(':')[0]]).concat(oneRow.subject_match_field.split('|').map((oneField) => oneField.split(':')[0])).concat(oneRow.object_match_field.split('|').map((oneField) => oneField.split(':')[0])), []))); const undeclared = usedList.filter((onePrefix) => declared.indexOf(onePrefix) === -1 && ['skos', 'semapv'].indexOf(onePrefix) === -1); return { pass: undeclared.length === 0 && declared.length >= 3, detail: `declared [${declared.join(', ')}], undeclared [${undeclared.join(', ')}]` }; }) }),
	runConjunct({ conjunctId: 'c_objectMatchFieldIsTupleString', title: "object_match_field is the Profile §4.5 tuple string on every row (EDUcoreHub:canonicalKey|EDUcoreHub:domainId for the crosswalk plugin's two supplied fields)", twinNameList: ['canonicalKeyAlone'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const bad = parsed.rowList.filter((oneRow) => oneRow.object_match_field !== 'EDUcoreHub:canonicalKey|EDUcoreHub:domainId'); return { pass: parsed.rowList.length > 0 && bad.length === 0, detail: `${bad.length} bad; sample ${parsed.rowList[0] ? parsed.rowList[0].object_match_field : ''}` }; }) }),
	runConjunct({ conjunctId: 'd_subjectMatchFieldDocumentPrefixForCrosswalk', title: 'subject_match_field names the DOCUMENT prefix for a crosswalk plugin (toyCrosswalk:HubGlobalId|toyCrosswalk:HubClassURI)', twinNameList: ['standardPrefixOnCrosswalkRow'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const bad = parsed.rowList.filter((oneRow) => oneRow.subject_match_field !== 'toyCrosswalk:HubGlobalId|toyCrosswalk:HubClassURI'); return { pass: parsed.rowList.length > 0 && bad.length === 0, detail: `${bad.length} bad` }; }) }),
	runConjunct({ conjunctId: 'd_subjectMatchFieldPropertyNameForStandard', title: "subject_match_field for a standard plugin is the standard's prefix + the PROPERTY NAME the walk read (toy:hubAnchorId — CURIE-safe, never a header text)", twinNameList: ['headerTextInMatchField'], shape: (scenario) => { scenario.spec.bridge = 'toyStandardPlugin'; }, judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const bad = parsed.rowList.filter((oneRow) => oneRow.subject_match_field !== 'toy:hubAnchorId'); return { pass: parsed.rowList.length > 0 && bad.length === 0, detail: `${bad.length} bad; sample ${parsed.rowList[0] ? parsed.rowList[0].subject_match_field : ''}` }; }) }),
	runConjunct({ conjunctId: 'e_noMappingDateUnlessSourceSuppliesIt', title: 'mapping_date is present ONLY if a declared source column supplied it — none in v1: no mapping_date column and no #mapping_date line', twinNameList: ['exporterStampsToday'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); if (parsed.error) { return { pass: false, detail: parsed.error }; } return { pass: parsed.columnList.indexOf('mapping_date') === -1 && !parsed.headerLineList.some((oneLine) => /^#mapping_date/.test(oneLine)), detail: `columns [${parsed.columnList.join(',')}]` }; }) }),
	refusalCase({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'f_unverifiedProviderRefusesExport', title: 'a mappingProvider not recorded as verified (verifiedBy null) → the export REFUSES by name (and so the re-judge run) — never a placeholder', shape: (scenario) => overrideDeclaration(scenario, (declaration) => { declaration.mappingProvider.verifiedBy = null; }), regex: /mappingProvider https:\/\/toy\.example\/crosswalk\/v1 is not recorded as verified-to-resolve \(verifiedBy null\)/, twinName: 'placeholderProvider', fileName: EXPORTER_FILE, find: '\tif (provider.verifiedBy === null || provider.verifiedBy === undefined) {', replace: '\tif (false && (provider.verifiedBy === null || provider.verifiedBy === undefined)) {' }),
	runConjunct({ conjunctId: 'g_authorIdAtSetLevelWhenDeclared', title: 'author_id / creator_id are emitted at set level whenever the declaration carries them (BR-058 SHOULD made checkable): a set-level slot supplied → a #author_id line', twinNameList: ['authorIdDropped'], shape: (scenario) => { scenario.frameworkMutationList.push({ modulePath: path.join(scenarioLib.FRAMEWORK_DIR, FRAMEWORK_FILE), find: '\t\t\t\t\t\t\t\t\t\tsubjectCuriePrefix: bridgeDeclaration.subjectCuriePrefix,\n', replace: "\t\t\t\t\t\t\t\t\t\tsubjectCuriePrefix: bridgeDeclaration.subjectCuriePrefix,\n\t\t\t\t\t\t\t\t\t\tauthorId: 'orcid:0000-0000-0000-0000',\n" }); }, judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); return { pass: !parsed.error && parsed.headerScalarOf('author_id') === 'orcid:0000-0000-0000-0000', detail: parsed.error || parsed.headerLineList.filter((oneLine) => /author/.test(oneLine)).join(' | ') || 'no author line' }; }) }),
	runConjunct({ conjunctId: 'h_subjectIdOneDeclaredPrefixColonFreeReference', title: 'every subject_id is the forged stableId VERBATIM: exactly ONE declared prefix + a colon-free reference (toy:property/…, never toy:toy:…) — RULING BR2', twinNameList: ['prefixPrependedAgain'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const declared = parsed.headerLineList.filter((oneLine) => /^#  \w+: /.test(oneLine)).map((oneLine) => oneLine.replace(/^#  (\w+): .*/, '$1')); const bad = parsed.rowList.filter((oneRow) => { const firstColon = oneRow.subject_id.indexOf(':'); const prefix = oneRow.subject_id.slice(0, firstColon); const reference = oneRow.subject_id.slice(firstColon + 1); return firstColon < 1 || declared.indexOf(prefix) === -1 || reference === '' || reference.indexOf(':') !== -1; }); return { pass: parsed.rowList.length > 0 && bad.length === 0, detail: bad.length ? `bad subject_id: ${bad.map((oneRow) => oneRow.subject_id).slice(0, 3).join(', ')}` : `${parsed.rowList.length} rows, e.g. ${parsed.rowList[0].subject_id}` }; }) }),
	refusalCase({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'i_stableIdWithoutDeclaredPrefixRefused', title: "a subject stableId that does not begin with the declared subjectCuriePrefix REFUSES the export by name (never repaired by prepending) — RULING BR2", shape: (scenario) => overrideDeclaration(scenario, (bridgeDeclaration) => { bridgeDeclaration.subjectCuriePrefix = 'toyx'; }), regex: /does not begin with the declared subjectCuriePrefix 'toyx:'/, twinName: 'prefixMismatchRepairedByPrepending', fileName: EXPORTER_FILE, find: "\t\tif (oneRecord.subjectStableId.indexOf(`${setLevelSlots.subjectCuriePrefix}:`) !== 0) {", replace: "\t\tif (false && oneRecord.subjectStableId.indexOf(`${setLevelSlots.subjectCuriePrefix}:`) !== 0) {" }),
	runConjunct({ conjunctId: 'subjectCensusBesideRowCount', title: 'the export report carries the SUBJECT census beside the row count (same-target shared leaves → fewer rows than subjects, by design — RULING 12:05 #9)', twinNameList: ['censusLineDropped'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const censusText = parsed.error ? undefined : parsed.headerScalarOf('subject_census'); const census = censusText ? JSON.parse(censusText) : null; return { pass: census !== null && census.rowCount === parsed.rowList.length && Number.isInteger(census.subjectCount), detail: parsed.error || censusText || 'no subject_census line' }; }) }),
	// ⟪B2 DEFECT #3 found by sssom-py on the first REAL export — RULING SABLE_RIVER 2026-08-16 (B3 cp2)⟫ the header is YAML a real validator parses
	runConjunct({ conjunctId: 'j_headerScalarsQuoted', title: 'EVERY metadata scalar (top-level, curie_map entries, extension_definitions items) is a QUOTED YAML scalar — the PROXY refuses an unquoted one; sssom-py did on the real export', twinNameList: ['unquotedScalars'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const scalarLineList = parsed.error ? [] : parsed.headerLineList.filter((oneLine) => /^#\s*(- )?[A-Za-z_][A-Za-z0-9_]*: .+$/.test(oneLine)); return { pass: !parsed.error && scalarLineList.length >= 12 && scalarLineList.every((oneLine) => /: ".*"$/.test(oneLine)), detail: parsed.error || `${scalarLineList.length} scalar lines, all quoted` }; }) }),
	runConjunct({ conjunctId: 'k_mappingSetIdIsUri', title: 'mapping_set_id is a URI over the block id (urn:educore:decisionBlock:<id>), never a bare hash', twinNameList: ['bareHashSetId'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); const value = parsed.error ? '' : parsed.headerScalarOf('mapping_set_id'); const blockId = runReport.blocks[0].decisionBlock.decisionBlockHash; return { pass: !parsed.error && value === `urn:educore:decisionBlock:${blockId}`, detail: parsed.error || `${value} (block ${blockId.slice(0, 12)}…)` }; }) }),
	runConjunct({ conjunctId: 'l_extensionDefinitionsDeclareEveryNonStandardSlot', title: 'every NON-STANDARD metadata slot and column the export uses is DECLARED under extension_definitions (slot_name + property IRI + type_hint)', twinNameList: ['extensionDefinitionsEmptied'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); if (parsed.error) { return { pass: false, detail: parsed.error }; } const declared = parsed.headerLineList.filter((oneLine) => /^#  - slot_name: /.test(oneLine)).map((oneLine) => JSON.parse(oneLine.replace('#  - slot_name: ', ''))); const standardSlotList = ['curie_map', 'mapping_provider', 'mapping_set_id', 'extension_definitions', 'subject_source', 'subject_source_version', 'object_source', 'object_source_version', 'subject_match_field', 'object_match_field', 'author_id', 'creator_id', 'mapping_date']; const usedNonStandard = parsed.headerLineList.filter((oneLine) => /^#[A-Za-z_]+: /.test(oneLine)).map((oneLine) => oneLine.replace(/^#([A-Za-z_]+): .*/, '$1')).filter((oneName) => standardSlotList.indexOf(oneName) === -1); const standardColumnList = ['subject_id', 'predicate_id', 'object_id', 'mapping_justification', 'object_label', 'confidence', 'subject_source', 'subject_source_version', 'object_source', 'object_source_version', 'subject_match_field', 'object_match_field', 'mapping_tool', 'mapping_tool_version']; const nonStandardColumnList = parsed.columnList.filter((oneColumn) => standardColumnList.indexOf(oneColumn) === -1); const undeclared = usedNonStandard.concat(nonStandardColumnList).filter((oneName) => declared.indexOf(oneName) === -1); const propertyLineList = parsed.headerLineList.filter((oneLine) => /^#    property: "https:\/\/w3id\.org\/EDUcore\/sssom\/extension#/.test(oneLine)); return { pass: declared.length >= 2 && undeclared.length === 0 && propertyLineList.length === declared.length, detail: `declared [${declared.join(', ')}]; used non-standard [${usedNonStandard.concat(nonStandardColumnList).join(', ')}]; undeclared [${undeclared.join(', ')}]` }; }) }),
	runConjunct({ conjunctId: 'm_sourcesAreCurieMapExpansions', title: 'subject_source / object_source are the curie_map EXPANSION IRIs of the subject prefix and the hub prefix (derived), and a URN scheme in use is declared in curie_map', twinNameList: ['sourceNameLiterals'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); if (parsed.error) { return { pass: false, detail: parsed.error }; } const curieMap = parsed.headerLineList.filter((oneLine) => /^#  \w+: /.test(oneLine)).reduce((soFar, oneLine) => ({ ...soFar, [oneLine.replace(/^#  (\w+): .*/, '$1')]: JSON.parse(oneLine.replace(/^#  \w+: /, '')) }), {}); const subjectPrefix = parsed.rowList[0].subject_id.split(':')[0]; const hubPrefix = parsed.headerScalarOf('object_match_field').split('|')[0].split(':')[0]; const subjectSource = parsed.headerScalarOf('subject_source'); const objectSource = parsed.headerScalarOf('object_source'); const rowsAgree = parsed.rowList.every((oneRow) => oneRow.subject_source === subjectSource && oneRow.object_source === objectSource); const urnDeclared = !/^urn:/.test(subjectSource) || curieMap.urn === 'urn:'; return { pass: subjectSource === curieMap[subjectPrefix] && objectSource === curieMap[hubPrefix] && rowsAgree && urnDeclared, detail: `subject_source ${subjectSource} (curie_map[${subjectPrefix}] ${curieMap[subjectPrefix]}); object_source ${objectSource} (curie_map[${hubPrefix}] ${curieMap[hubPrefix]}); urn declared ${urnDeclared}` }; }) }),
	runConjunct({ conjunctId: 'n_sssomPyValidatesWhenPresent', title: `sssom-py \`sssom validate\` exits 0 on the export when its venv is present (${SSSOM_PY_LABEL}); the PROXY carries the conjunct otherwise`, twinNameList: ['unquotedScalars', 'bareHashSetId'], judge: succeeded((runReport, outcome, scenario) => { const parsed = parsedOf(outcome, scenario); if (parsed.error) { return { pass: false, detail: `PROXY: ${parsed.error}` }; } if (!SSSOM_PY_PRESENT) { return { pass: true, detail: `PROXY only — sssom-py absent at ${SSSOM_PY_BIN_PATH} (ONE-MACHINE)` }; } const validated = require('child_process').spawnSync(SSSOM_PY_BIN_PATH, ['validate', outcome.runReport.sssomExportPath], { encoding: 'utf8' }); return { pass: validated.status === 0, detail: validated.status === 0 ? 'sssom validate exit 0' : `sssom validate exit ${validated.status}: ${(validated.stderr || '').split('\n').filter((oneLine) => /ERROR|Error/.test(oneLine)).slice(-2).join(' | ').slice(0, 300)}` }; }) }),
];
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'a_tsvParses_PROXY', twinName: 'deleteMandatoryColumn', fileName: EXPORTER_FILE, find: "const COLUMN_LIST = Object.freeze([\n\t'subject_id',\n\t'predicate_id',", replace: "const COLUMN_LIST = Object.freeze([\n\t'subject_id'," });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'b_everyPrefixInCurieMap', twinName: 'dropHubPrefixFromCurieMap', fileName: FRAMEWORK_FILE, find: "\t\t\t\t\t\t\t\t\tconst curieMap = { [bridgeDeclaration.subjectCuriePrefix]: `urn:educore:${bridgeDeclaration.standardKey}:`, [bridgeDeclaration.sourceCuriePrefix.prefix]: bridgeDeclaration.sourceCuriePrefix.iri, [OBJECT_MATCH_FIELD_HUB_PREFIX]: `urn:educore:hub:${block.header.hubName}:` };", replace: "\t\t\t\t\t\t\t\t\tconst curieMap = { [bridgeDeclaration.subjectCuriePrefix]: `urn:educore:${bridgeDeclaration.standardKey}:`, [bridgeDeclaration.sourceCuriePrefix.prefix]: bridgeDeclaration.sourceCuriePrefix.iri };" });
// under dropHubPrefixFromCurieMap the exporter REFUSES (undeclared prefix) → the run fails → the conjunct is red (a refusal is not a pass); the exporter's own refusal is the production guard and the twin shows the gate would ALSO catch a TSV missing it: register a second twin that disables the exporter's prefix check as well
scenarioTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'b_everyPrefixInCurieMap', twinName: 'dropHubPrefixAndDisableExporterCheck', leverKind: 'productionMutation', mutate: (scenario) => {
	scenario.frameworkMutationList.push({ modulePath: path.join(scenarioLib.FRAMEWORK_DIR, FRAMEWORK_FILE), find: "\t\t\t\t\t\t\t\t\tconst curieMap = { [bridgeDeclaration.subjectCuriePrefix]: `urn:educore:${bridgeDeclaration.standardKey}:`, [bridgeDeclaration.sourceCuriePrefix.prefix]: bridgeDeclaration.sourceCuriePrefix.iri, [OBJECT_MATCH_FIELD_HUB_PREFIX]: `urn:educore:hub:${block.header.hubName}:` };", replace: "\t\t\t\t\t\t\t\t\tconst curieMap = { [bridgeDeclaration.subjectCuriePrefix]: `urn:educore:${bridgeDeclaration.standardKey}:`, [bridgeDeclaration.sourceCuriePrefix.prefix]: bridgeDeclaration.sourceCuriePrefix.iri };" });
	scenario.frameworkMutationList.push({ modulePath: path.join(scenarioLib.FRAMEWORK_DIR, EXPORTER_FILE), find: '\tif (undeclaredMatchField !== undefined) {', replace: '\tif (false && undeclaredMatchField !== undefined) {' });
} });
conjunctList[1].twinNameList = ['dropHubPrefixFromCurieMap', 'dropHubPrefixAndDisableExporterCheck'];
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'c_objectMatchFieldIsTupleString', twinName: 'canonicalKeyAlone', fileName: FRAMEWORK_FILE, find: ".map((oneField) => `${OBJECT_MATCH_FIELD_HUB_PREFIX}:${oneField}`).join('|'));", replace: ".map((oneField) => `${OBJECT_MATCH_FIELD_HUB_PREFIX}:canonicalKey`).slice(0, 1).join('|'));" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'd_subjectMatchFieldDocumentPrefixForCrosswalk', twinName: 'standardPrefixOnCrosswalkRow', fileName: FRAMEWORK_FILE, find: "\t\t\tconst prefix = bridgeDeclaration.sourceCuriePrefix.prefix;\n\t\t\treturn TUPLE_FIELD_LIST", replace: "\t\t\tconst prefix = bridgeDeclaration.subjectCuriePrefix;\n\t\t\treturn TUPLE_FIELD_LIST" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'd_subjectMatchFieldPropertyNameForStandard', twinName: 'headerTextInMatchField', fileName: FRAMEWORK_FILE, find: "\t\t\t\t.map((oneField) => `${prefix}:${bridgeDeclaration.tupleFieldColumnMap[oneField].column}`)", replace: "\t\t\t\t.map((oneField) => `${prefix}:${bridgeDeclaration.matchBasis === 'standard' ? 'Hub Global Id' : bridgeDeclaration.tupleFieldColumnMap[oneField].column}`)" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'e_noMappingDateUnlessSourceSuppliesIt', twinName: 'exporterStampsToday', fileName: EXPORTER_FILE, find: "\theaderLineList.push(`#subject_census:", replace: "\theaderLineList.push('#mapping_date: \"2026-08-16\"');\n\theaderLineList.push(`#subject_census:" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'g_authorIdAtSetLevelWhenDeclared', twinName: 'authorIdDropped', fileName: EXPORTER_FILE, find: "\tif (isNonEmptyString(setLevelSlots.authorId)) {\n\t\theaderLineList.push(`#author_id: ${yamlScalar(setLevelSlots.authorId)}`);\n\t}", replace: "\tif (false && isNonEmptyString(setLevelSlots.authorId)) {\n\t\theaderLineList.push(`#author_id: ${yamlScalar(setLevelSlots.authorId)}`);\n\t}" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'h_subjectIdOneDeclaredPrefixColonFreeReference', twinName: 'prefixPrependedAgain', fileName: EXPORTER_FILE, find: '\t\t\tsubject_id: oneRecord.subjectStableId,', replace: '\t\t\tsubject_id: `${setLevelSlots.subjectCuriePrefix}:${oneRecord.subjectStableId}`,' });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'j_headerScalarsQuoted', twinName: 'unquotedScalars', fileName: EXPORTER_FILE, find: 'const yamlScalar = (value) => JSON.stringify(String(value));', replace: 'const yamlScalar = (value) => String(value);' });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'n_sssomPyValidatesWhenPresent', twinName: 'unquotedScalars', fileName: EXPORTER_FILE, find: 'const yamlScalar = (value) => JSON.stringify(String(value));', replace: 'const yamlScalar = (value) => String(value);' });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'k_mappingSetIdIsUri', twinName: 'bareHashSetId', fileName: EXPORTER_FILE, find: "const MAPPING_SET_ID_URN_BASE = 'urn:educore:decisionBlock:';", replace: "const MAPPING_SET_ID_URN_BASE = '';" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'n_sssomPyValidatesWhenPresent', twinName: 'bareHashSetId', fileName: EXPORTER_FILE, find: "const MAPPING_SET_ID_URN_BASE = 'urn:educore:decisionBlock:';", replace: "const MAPPING_SET_ID_URN_BASE = '';" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'l_extensionDefinitionsDeclareEveryNonStandardSlot', twinName: 'extensionDefinitionsEmptied', fileName: EXPORTER_FILE, find: "const EXTENSION_SLOT_NAME_LIST = Object.freeze(['mapping_provider_verified_by', 'label_table', 'channel_assertion', 'subject_census', 'source_label', 'predicate_asserted_by']);", replace: "const EXTENSION_SLOT_NAME_LIST = Object.freeze([]);" });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'm_sourcesAreCurieMapExpansions', twinName: 'sourceNameLiterals', fileName: EXPORTER_FILE, find: '\tconst subjectSourceIri = curieMap[setLevelSlots.subjectCuriePrefix];\n\tconst objectSourceIri = objectPrefix === null ? undefined : curieMap[objectPrefix];', replace: '\tconst subjectSourceIri = setLevelSlots.subjectSource;\n\tconst objectSourceIri = setLevelSlots.objectSource;' });
frameworkMutationTwin({ registry: twinRegistry, gateId: GATE_ID, conjunctId: 'subjectCensusBesideRowCount', twinName: 'censusLineDropped', fileName: EXPORTER_FILE, find: "\theaderLineList.push(`#subject_census: ${yamlScalar(JSON.stringify({ subjectCount: subjectSet.size, rowCount: rowList.length, note: 'rows are per (subject stableId, predicate, object); several source subjects sharing one leaf yield ONE row' }))}`);", replace: '\tvoid subjectSet;' });

const gateDeclarationList = [{ gateId: GATE_ID, title: `SSSOM/TSV validity — ${VALIDATOR_LABEL}`, conjunctList }];

runGateFamily(
	{ harness, familyName: GATE_ID, gateDeclarationList, twinRegistry, makeSubject: scenarioLib.makeScenario, cloneSubject: scenarioLib.cloneScenario, expectedConjunctCount: 16 },
	() => harness.report(),
);
