'use strict';

const moduleName = __filename.replace(__dirname + '/', '').replace(/.js$/, '');

// baselineStore.js — freeze + read the immutable baseline (Phase 0, deliverable 5; N2).
//
// The current golden is frozen as an immutable baseline: a metadata file (fingerprint hashes, counts,
// manifestKey, builtAt) + a snapshot file (the full elementManifest, so future phases diff against it
// WITHOUT rebuilding the golden). Both are written read-only (0444). freezeBaseline REFUSES to
// overwrite an existing baseline of the same label unless force===true — the baseline is preserved,
// never silently clobbered (N2). The baseline lives in the build store dir, isolated from any graph.
//
// Async style: fs via callbacks inside taskListPlus/pipeRunner. No async/await, no try/catch for
// control flow. camelCase.
//
// @concept: [[BaselineFreeze]]
// @concept: [[ImmutableBaseline]]

const path = require('path');
const fs = require('fs');
const { pipeRunner, taskListPlus } = new require('qtools-asynchronous-pipe-plus')();

const READONLY_MODE = 0o444;
const WRITABLE_MODE = 0o644;

const moduleFunction =
	({ moduleName } = {}) =>
	({ projectRoot, baselineDir } = {}) => {
		const { xLog } = process.global;
		const baseDir =
			baselineDir || path.join(projectRoot, 'dataStores', 'phase0Baselines');

		const metaPathFor = (label) => path.join(baseDir, `${label}.baseline.json`);
		const snapshotPathFor = (label) => path.join(baseDir, `${label}.snapshot.json`);

		// freezeBaseline({label, manifestKey, fingerprint, buildResult, force?}, cb)
		//   -> { snapshotFile, metaFile, immutable:true }
		const freezeBaseline = (
			{ label, manifestKey, fingerprint, buildResult, force = false } = {},
			callback,
		) => {
			if (!label || !manifestKey || !fingerprint) {
				callback('baselineStore.freezeBaseline: label, manifestKey, fingerprint are required');
				return;
			}
			const metaFile = metaPathFor(label);
			const snapshotFile = snapshotPathFor(label);

			const taskList = new taskListPlus();

			// ensure baseline dir exists
			taskList.push((args, next) => {
				fs.mkdir(baseDir, { recursive: true }, (err) => next(err ? `mkdir ${baseDir}: ${err.message}` : '', args));
			});

			// N2 — refuse to clobber an existing immutable baseline unless forced
			taskList.push((args, next) => {
				fs.access(metaFile, fs.constants.F_OK, (missing) => {
					if (!missing && !force) {
						next(
							`baselineStore: baseline '${label}' already exists at ${metaFile} and is immutable — ` +
								`refusing to overwrite (N2). Pass force to replace deliberately.`,
						);
						return;
					}
					next('', args);
				});
			});

			// if forcing over an existing read-only file, restore write permission first
			taskList.push((args, next) => {
				[metaFile, snapshotFile].forEach((oneFile) => {
					if (fs.existsSync(oneFile)) {
						fs.chmodSync(oneFile, WRITABLE_MODE);
					}
				});
				next('', args);
			});

			// write the snapshot (full elementManifest)
			taskList.push((args, next) => {
				const snapshotBody = JSON.stringify(
					{
						label,
						manifestKey,
						fingerprint: fingerprint.fingerprint,
						elementManifest: fingerprint.elementManifest,
					},
					null,
					0,
				);
				fs.writeFile(snapshotFile, snapshotBody, (err) =>
					next(err ? `write snapshot: ${err.message}` : '', args),
				);
			});

			// write the metadata
			taskList.push((args, next) => {
				const metaBody = JSON.stringify(
					{
						label,
						manifestKey,
						fingerprint: fingerprint.fingerprint,
						nodeFingerprint: fingerprint.nodeFingerprint,
						edgeFingerprint: fingerprint.edgeFingerprint,
						nodeCount: fingerprint.nodeCount,
						edgeCount: fingerprint.edgeCount,
						ignoreOwnerStamp: fingerprint.ignoreOwnerStamp,
						ignoreEmbedding: fingerprint.ignoreEmbedding,
						scope: fingerprint.scope,
						buildSummary: buildResult
							? {
									destination: buildResult.destination,
									blockCount: buildResult.blockCount,
									nodesMerged: buildResult.replayResult
										? buildResult.replayResult.nodesMerged
										: null,
									edgesMerged: buildResult.replayResult
										? buildResult.replayResult.edgesMerged
										: null,
								}
							: null,
						snapshotFile: path.basename(snapshotFile),
						frozenNote:
							'immutable baseline (N2); generated by edf-gate -freezeBaseline. builtAt omitted by design — it is non-deterministic and not part of content identity.',
					},
					null,
					2,
				);
				fs.writeFile(metaFile, metaBody, (err) =>
					next(err ? `write meta: ${err.message}` : '', args),
				);
			});

			// mark both immutable (0444)
			taskList.push((args, next) => {
				fs.chmod(snapshotFile, READONLY_MODE, (e1) => {
					fs.chmod(metaFile, READONLY_MODE, (e2) => {
						next(e1 || e2 ? `chmod readonly: ${e1 || e2}` : '', args);
					});
				});
			});

			pipeRunner(taskList.getList(), {}, (err) => {
				if (err) {
					callback(err);
					return;
				}
				xLog.verbose(`[baselineStore] froze baseline '${label}' -> ${metaFile}`);
				callback('', { snapshotFile, metaFile, immutable: true });
			});
		};

		// readBaseline({label}, cb) -> { meta, snapshot }
		const readBaseline = ({ label } = {}, callback) => {
			const metaFile = metaPathFor(label);
			const snapshotFile = snapshotPathFor(label);
			const taskList = new taskListPlus();

			taskList.push((args, next) => {
				fs.readFile(metaFile, 'utf8', (err, text) => {
					if (err) { next(`baselineStore.readBaseline meta: ${err.message}`); return; }
					next('', { ...args, meta: JSON.parse(text) });
				});
			});
			taskList.push((args, next) => {
				fs.readFile(snapshotFile, 'utf8', (err, text) => {
					if (err) { next(`baselineStore.readBaseline snapshot: ${err.message}`); return; }
					next('', { ...args, snapshot: JSON.parse(text) });
				});
			});

			pipeRunner(taskList.getList(), {}, (err, args) => {
				if (err) { callback(err); return; }
				callback('', { meta: args.meta, snapshot: args.snapshot });
			});
		};

		return { freezeBaseline, readBaseline, metaPathFor, snapshotPathFor, baseDir };
	};

module.exports = moduleFunction({ moduleName });
